class Vehicle:
    def __init__(self):
        self.speed = ...
        self.color = ...
        self.model = ...
        
    def turn_on(self):
        ...
        
    def turn_off(self):
        ...
        
    def gear_change(self):
        ...
        
    
jimbo= Vehicle()
pride= Vehicle()