name: Run Python Script

on:
  workflow_dispatch:

env:
    my_token: ${{ secrets.TOKEN }}

jobs:
    run-pythn:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11

            - name: Run Python Script
              run: |
                pip install requests
                python telegrambot_classification.py
